### ISSUE TITLE
Argument 1 passed to Hanson\\Foundation\\Http::__construct() must be an instance of Hanson\\Foundation\\Foundation, null given, called in /var/www/epmms2-award/vendor/hanson/foundation-sdk/src/AbstractAPI.php on line 32

### ISSUE THREAD

**Issue by ysw121512** [justmd5/duoduoke-sdk#10]
{
    "name": "Exception",
    "message": "Argument 1 passed to Hanson\\Foundation\\Http::__construct() must be an instance of Hanson\\Foundation\\Foundation, null given, called in /var/www/epmms2-award/vendor/hanson/foundation-sdk/src/AbstractAPI.php on line 32",
    "code": -1,
    "type": "TypeError",
    "file": "/var/www/epmms2-award/vendor/hanson/foundation-sdk/src/Http.php",
    "line": 55,
    "stack-trace": [
        "#0 /var/www/epmms2-award/vendor/hanson/foundation-sdk/src/AbstractAPI.php(32): Hanson\\Foundation\\Http->__construct(NULL)",
        "#1 /var/www/epmms2-award/vendor/justmd5/duoduoke-sdk/src/Api.php(52): Hanson\\Foundation\\AbstractAPI->getHttp()",
        "#2 /var/www/epmms2-award/vendor/justmd5/duoduoke-sdk/src/DuoDuoKe.php(25): Justmd5\\DuoDuoKe\\Api->request('pdd.ddk.goods.r...', Array)",
        "#3 /var/www/epmms2-award/api/controllers/PddController.php(151): Justmd5\\DuoDuoKe\\DuoDuoKe->request('pdd.ddk.goods.r...', Array)",
        "#4 [internal function]: api\\controllers\\PddController->actionIndex()",
        "#5 /var/www/epmms2-award/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)",
        "#6 /var/www/epmms2-award/vendor/yiisoft/yii2/base/Controller.php(157): yii\\base\\InlineAction->runWithParams(Array)",
        "#7 /var/www/epmms2-award/vendor/yiisoft/yii2/base/Module.php(528): yii\\base\\Controller->runAction('', Array)",
        "#8 /var/www/epmms2-award/vendor/yiisoft/yii2/web/Application.php(103): yii\\base\\Module->runAction('pdd', Array)",
        "#9 /var/www/epmms2-award/vendor/yiisoft/yii2/base/Application.php(386): yii\\web\\Application->handleRequest(Object(yii\\web\\Request))",
        "#10 /var/www/epmms2-award/api/web/index.php(17): yii\\base\\Application->run()",
        "#11 {main}"
    ],
    "success": false
}

**Comment by justmd5** [comment]
配置和请求参数发一下，只贴异常，看不出来什么问题

**Comment by ysw121512** [comment]
您好！我们当时的情况是这样的，当天上午我还在正常使用您的包进行开发测试，下午更新了一下composer包版本结果出错了，后来经过排查发现更新完之后"hanson/foundation-sdk": "^3.0",这个包的版本发生变化导致。于是我们后来就在composer.json里面指定了这个包的版本，现在配置如下："justmd5/duoduoke-sdk": "^2.0",
"hanson/foundation-sdk": "~3.0.5",
正常使用。


我们的开发环境是：yii2框架，PHP7.4。


非常感谢您的包支持，
愿您越做越好。










在 2020-06-15 09:08:22，"丁海军" <notifications@github.com> 写道：

配置和请求参数发一下，只贴异常，看不出来什么问题

**Comment by ysw121512** [comment]
好像是3.0.5版本有错误，然后我们手动指定了一下3.0的版本




| |
郑州科壮元信息技术有限公司
|
|
邮箱：ysw0110@163.com
|

签名由 网易邮箱大师 定制

On 06/15/2020 09:27, 郑州科壮元信息技术有限公司 wrote:







您好！我们当时的情况是这样的，当天上午我还在正常使用您的包进行开发测试，下午更新了一下composer包版本结果出错了，后来经过排查发现更新完之后"hanson/foundation-sdk": "^3.0",这个包的版本发生变化导致。于是我们后来就在composer.json里面指定了这个包的版本，现在配置如下："justmd5/duoduoke-sdk": "^2.0",
"hanson/foundation-sdk": "~3.0.5",
正常使用。


我们的开发环境是：yii2框架，PHP7.4。


非常感谢您的包支持，
愿您越做越好。










在 2020-06-15 09:08:22，"丁海军" <notifications@github.com> 写道：

配置和请求参数发一下，只贴异常，看不出来什么问题

**Comment by justmd5** [comment]
已经查到问题，马上修复，另外，建议使用readme里边的[pinduoduo-sdk](https://github.com/justmd5/pinduoduo-sdk),更换成本较低。当前项目只做bug fix

**Comment by justmd5** [comment]
请稍后使用最新版本

**Comment by justmd5** [comment]
已经修复，请使用最新版本
